version: "3.3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: reservas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    image: python:3.12
    working_dir: /app
    volumes:
      - ./:/app
    command: >
      bash -c "pip install -r requirements.txt &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
    depends_on:
      - db

volumes:
  pgdata:
