# Generated by Django 6.1 on 2026-08-11 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(default='Perú', max_length=100)),
                ('habitaciones', models.PositiveSmallIntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'propiedades',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huesped', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.propiedad')),
            ],
        ),
    ]
