# Generated by Django 6.1 on 2026-08-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_adjunto'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['propiedad', 'fecha_inicio'], name='idx_reserva_prop_inicio'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado'], name='idx_reserva_estado'),
        ),
    ]
